### ISSUE TITLE
not working from windows

### ISSUE THREAD

**Issue by vstreammedia** [agnat/node_wake_on_lan#4]
The sample code works perfectly fine from MacOS but is not running on Windows. any idea why?
same Node versions on both machines.

Regards,
Andrés.

**Comment by agnat** [comment]
No clue really...

Some sort of firewall preventing outgoing UDP broadcasts?

Maybe use wireshark to make sure windows actually sends a packet and it looks the same as on mac os?

**Comment by mwittig** [comment]
Hi guys! Apparently, the problem is the routing behaviour for the global broadcast address on Windows as the IP packets will only be propagated through the first network interface found. The following [article](https://social.technet.microsoft.com/Forums/windows/en-US/72e7387a-9f2c-4bf4-a004-c89ddde1c8aa/how-to-fix-the-global-broadcast-address-255255255255-behavior-on-windows) describes the matter. Work-around: Set the "address" property to the broadcast address for your local network / the subnet. Here is an example which works for my setup.

```
wol.wake(theMac, { address: "192.168.178.255" }, wakeCB);
```

EDIT: If you're not sure how to calculate the broadcast address see [this article](http://www.wikihow.com/Calculate-Network-and-Broadcast-Address) or simply use an [online calculator](http://jodies.de/ipcalc)

**Comment by agnat** [comment]
Thanks @mwittig. This is really helpful. IP address and net mask are available at runtime using [`os.networkInterfaces()`](https://nodejs.org/api/os.html#os_os_networkinterfaces).

**Comment by mwittig** [comment]
Yes, `os.networkInterfaces()` can be used to collect all netmasks to send the wol packet via each interface. Note, however, "netmask" is not included in node v0.10. Unfortunately, I  have still to support v0.10 in some of my projects. See also https://github.com/nodejs/node-v0.x-archive/issues/5731

**Comment by agnat** [comment]
I added a [note](https://github.com/agnat/node_wake_on_lan/tree/master#windows-notes) to the README in 1c4f1ed01d6fe427d8bb4b98c7a469c001d041c8.
